name: Build Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_URL }}
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}
      - name: Build and Push to Gitea
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: smam_admin/portfolio-website:latest