name: Build Portfolio Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_URL }}
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.GITEA_URL }}/smam_admin/portfolio-website:latest -t ${{ secrets.GITEA_URL }}/smam_admin/portfolio-website:${{ github.run_number }} .
      - name: Push Docker Image
        run: docker push ${{ secrets.GITEA_URL }}/smam_admin/portfolio-website